bg_review/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ReviewList.as_view(), name='home'),
    path('<slug:slug>/', views.single_review, name='single_review'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
        views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>', views.comment_delete, name='comment_delete'),
]

p4_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('bg_review.urls'), name='bg-review-urls'),
]

bg_review/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Draft"), (1, "Published"))
RATE = ((0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"))


# Model for board games
class BoardGame(models.Model):
    """
    Stores a single board game entry
    (related to :model:`auth.User`)
    """
    bg_name = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(
        User, on_delete=models.RESTRICT, related_name="user")
    created_on = models.DateTimeField(auto_now_add=True)
    bg_image = CloudinaryField('image', default='placeholder')
    updated_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on", "approved"]

    def __str__(self):
        return self.bg_name


# Model for reviews
class Review(models.Model):
    """
    Stores a single review for a specific board game entry
    (related to :model:`auth.User`, :model: `bg_review.BoardGame`)
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.RESTRICT, related_name="author")
    bg_name = models.ForeignKey(
        BoardGame, on_delete=models.CASCADE, related_name="bg")
    review_image = CloudinaryField('image', default='placeholder')
    created_on = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    short = models.TextField(default="an_excerpt")

    class Meta:
        ordering = ["created_on", "approved"]

    def __str__(self):
        return self.title


# Model for rating
class Rating(models.Model):
    """
    Stores a single rating for a specific review entry
    (related to :model:`auth.User`, :model: `bg_review.Review`)
    """
    visitor = models.ForeignKey(
        User, on_delete=models.RESTRICT, related_name="visitor")
    rating = models.IntegerField(choices=RATE, default=0)
    review = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="review")
    help_text = "Please rate the board game from  0 = horrible board\
        game to 10 = fantastic board game."
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return f"{self.rating} as rating for {self.review} by {self.visitor}"


# Model for user comments
class Comment(models.Model):
    """
    Stores a single comment for a specific review entry 
    (related to :model:`auth.User`, :model: `bg_review.Review`)
    """
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(
        User, on_delete=models.RESTRICT, related_name="writer")
    comment = models.ForeignKey(
        Review, on_delete=models.CASCADE, related_name="comments")
    updated_on = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["created_on", "approved"]

    def __str__(self):
        return f"Comment added by {self.writer}"

bg_review/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

bg_review/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import BoardGame, Review, Rating, Comment
from .forms import CommentForm


class ReviewList(generic.ListView):
    """
    All reviews displayed in a list
    (Displays: :model:`bg_review.Review`)
    **Context**
    ``queryset``
        All published instances of :model:`bg_review.Review`
    ``paginate_by``
        Number of posts per page.
    **Template:**
    :template:`index.html`
    """
    model = Review
    queryset = Review.objects.order_by('-created_on')
    template_name = "index.html"
    paginate_by = 6


def single_review(request, slug):
    """
    All details for one review are displayed
    (Displays: :model:`bg_review.Review`, 
    :model:`bg_review.Rating` and :model:`bg_review.Comment`)
    **Context**
     ``review``
        An instance of :model:`bg_review.Review`.
    ``comments``
        All approved comments related to the review.
    ``ratings``
        All ratings related to the review.
    **Template:**
    :template:`single_review.html`
    """
    queryset = Review.objects.filter(status=1)
    review = get_object_or_404(queryset, slug=slug)
    ratings = Rating.objects.filter(review=review)
    ratings_count = 0
    ratings_sum = 0
    for rating in ratings:
        ratings_count += 1
        ratings_sum += rating.rating
    if ratings_count > 0:
        ratings_average = ratings_sum / ratings_count
    else:
        ratings_average = "Not rated yet."
    comments = review.comments.all().order_by("-created_on")
    comment_count = review.comments.filter(approved=True).count
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.writer = request.user
            comment.comment = review
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(request, 'single_review.html', {
                    "review": review,
                    "comments": comments,
                    "comment_count": comment_count,
                    "comment_form": comment_form,
                    "ratings_count": ratings_count,
                    "ratings_average": ratings_average,
            },)


def comment_edit(request, slug, comment_id):
    """
    Edit comments
    (Displays: :model:`bg_review.Review`, :model:`bg_review.Comment`)
    **Context**
    ``review``
        An instance of :model:`bg_review.Review`.
    ``comment``
        A single comment related to the review.
    ``comment_form``
        An instance of :form:`bg_review.CommentForm`
    """
    if request.method == "POST":

        queryset = Review.objects.filter(status=1)
        review = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.writer == request.user:
            comment = comment_form.save(commit=False)
            comment.comment = review
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error updating comment!')

    return HttpResponseRedirect(reverse('single_review', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    Delete comments
    (Displays: :model:`bg_review.Review`, :model:`bg_review.Comment`)
    **Context**
    ``review``
        An instance of :model:`bg_review.Review`.
    ``comment``
        A single comment related to the review.
    """
    queryset = Review.objects.filter(status=1)
    review = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.writer == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('single_review', args=[slug]))

templates/base.html
{% load static %}

{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}


<!DOCTYPE html>
<html class="h-100" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Title -->
    <title>Board Game Review Page</title>
    <!-- Font Family -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <!-- Fontawesome-->
    <script src="https://kit.fontawesome.com/b5633ebce6.js" crossorigin="anonymous"></script>
    <!-- Bootstrap 5.3.1 CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column h-100 main-bg">
    <!-- Header -->
    <header>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navbarText" class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == home_url %}active{% endif %}" aria-current="page"
                                href="{% url 'home' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" 
                            href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page" 
                            href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" 
                            href="{% url 'account_login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div>
                    <span class="navbar-text text-muted">
                        Reviews of board games
                    </span>
                </div>
            </div>
        </nav>
        <!-- Display Django messages -->
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible
                        fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close"
                            data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </header>
    

    <main>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>
    

    <!-- Footer -->
    <footer class="navbar nav-color fixed-bottom">
        <div class="container-fluid">
            <h6>Made by R</h6>
            <p> Join us: <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-square-instagram"></i>
                <i class="fa-brands fa-square-x-twitter"></i>
            </p>
            <h6>BG Reviews</h6>
        </div>
    </footer>

    <!-- Bootstrap 5.3.1 JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    {% block extras %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- content start-->
<div>
    
</div>
<div class="main mx-5 my-5">
    <div id="welcome" class="text-center">
        <h1>Hello Board Gamers or those who want to become one!<br>Welcome to our review page!</h1>
        <p>Here everyone is welcomed to read or contribute according to our community standards of respect and a friendly with each other.</p>    
    </div>
    
    <div id="sep-line"></div>
</div>

<div class="container-fluid">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left whole-card">
            <div class="row">
                {% for single_review in review_list %}
                <div class="col-md-4">
                    <div class="mb-4">
                        <div class="card-body">
                            <div>
                                {% if "placeholder" in single_review.bg_name.bg_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                {% else %}
                                    <img class="card-img-top" src=" {{ single_review.bg_name.bg_image.url  }}" alt="{{ single_review.bg_name }}">
                                {% endif %}
                                <div class="d-flex justify-content-between">
                                    <p class="author">Author: {{ single_review.author }}</p>
                                    <p class="createdon">Date: {{ single_review.created_on }}</p>
                                </div>
                                <div>
                                    <p class="boardgame">{{ single_review.bg_name }}</p>
                                </div>
                            </div>
                            <a href="{% url 'single_review' single_review.slug %}" class="review-link link">
                                <h2 class="card-title">{{ single_review.title }}</h2>
                                <p class="card-text">{{ single_review.short }}</p>
                            </a>
                            <hr>
                            <p class="card-text text-muted h6">{{ review.created_on}}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    
    
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a class="link" href="?page={{ page_obj.previous_page_number }}">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a class="link" href="?page={{ page_obj.next_page_number }}"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
<!-- content end -->
{%endblock%}

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}

templates/single_review.html
{% extends 'base.html' %} 

{% load static %}
{% load crispy_forms_tags %}

{% block content %}



<div class="container">
  <div class="row g-0">
      <div class="col-md-6 review_titles">
          <!-- Review title -->
          <h1 class="review-title">{{ review.title }}</h1>
          <!-- Review author | created date -->
          <p class="review-subtitle">{{ review.author }} | {{ review.created_on }}</p>
      </div>
      <div class="d-md-block col-md-6">
        {% if "placeholder" in review.review_image.url %}
          <img class="single_rev-image" src="{% static 'images/default.jpg' %}" alt="placeholder image" >
        {% else %}
          <img class="single_rev-image" src="{{ review.review_image.url }}" alt="{{ review.title }}">
        {% endif %}
      </div>
  </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content inside card-text | safe filter -->
                <p class="card-text">
                    {{ review.content | safe }}
                </p>
            </div>
        </div>
    </div>
    <div class="row">
      <!-- Display count of comments -->
      <div class="col-6 text-start">
        <strong class="text-secondary">
          <i class="far fa-comments"></i> {{ comment_count }}
        </strong>
      </div>
      <!-- Display rating -->
      <div class="col-6 text-end">
        <strong class="text-secondary">
          <i class="fa-solid fa-star-half-stroke"></i>
          {{ ratings_average }} || Total number of ratings: {{ ratings_count }}
        </strong>
      </div>
    </div>    

  <!-- Display Comments -->
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3">
      <h3>Comments:</h3>
      <div class="card-body">
        {% for comment in comments %}
        <div class="p-2 comments {% if not comment.approved and comment.writer == user %}faded{% elif not comment.approved %}d-none{% endif %}">
          <p class="font-weight-bold">
            {{ comment.writer }}
            <span class="font-weight-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.content | linebreaks }}
          </div>
          {% if not comment.approved and comment.writer == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %}
          {% if user.is_authenticated and comment.writer == user %}
            <button class="btn btn-delete" comment_id="{{ comment.id }}">Delete</button>
            <button class="btn btn-edit" comment_id="{{ comment.id }}">Edit</button>
          {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
      <div class="card-body">
        {% if user.is_authenticated %}
        <h3>Leave a comment:</h3>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit" class="btn btn-lg">Submit</button>
        </form>
        {% else %}
        <p><a class="link" href="{% url 'account_login' %}">Log in</a> to leave a comment</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}